Repository google-ai-edge/ai-edge-torch, pull requests merged in 2024-08, with the labels that each got.

#125 Update README.md
  README.md
Labels: CLA:yes

#130 Update TinyLlama goldens in forward pass
  ai_edge_torch/generative/examples/tiny_llama/tiny_llama_lm_logits.pt
Labels: CLA:yes

#156 Relax python version requirements.
  setup.py
Labels: ci:run, CLA:yes

#172 Fix batch norm when weight/bias is None
  ai_edge_torch/_convert/fx_passes/optimize_layout_transposes_pass/layout_rewrite.py
Labels: ci:run, ci:model-coverage, CLA:yes
